# Generated by Django 5.2.7 on 2025-10-14 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menonight', '0003_gallery'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Gallery',
            new_name='GalleryImage',
        ),
    ]
